/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/main/login`; params?: Router.UnknownInputParams; } | { pathname: `/main/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/main/SignupPassword`; params?: Router.UnknownInputParams; } | { pathname: `/main/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/modal/Profile-form`; params?: Router.UnknownInputParams; } | { pathname: `/routes/join`; params?: Router.UnknownInputParams; } | { pathname: `/routes/meet`; params?: Router.UnknownInputParams; } | { pathname: `/routes/profile`; params?: Router.UnknownInputParams; } | { pathname: `/routes/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/routes/subroutes/meeting`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/main/login`; params?: Router.UnknownOutputParams; } | { pathname: `/main/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `/main/SignupPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/main/verify-otp`; params?: Router.UnknownOutputParams; } | { pathname: `/modal/Profile-form`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/join`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/meet`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/subroutes/meeting`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/main/login${`?${string}` | `#${string}` | ''}` | `/main/Signup${`?${string}` | `#${string}` | ''}` | `/main/SignupPassword${`?${string}` | `#${string}` | ''}` | `/main/verify-otp${`?${string}` | `#${string}` | ''}` | `/modal/Profile-form${`?${string}` | `#${string}` | ''}` | `/routes/join${`?${string}` | `#${string}` | ''}` | `/routes/meet${`?${string}` | `#${string}` | ''}` | `/routes/profile${`?${string}` | `#${string}` | ''}` | `/routes/schedule${`?${string}` | `#${string}` | ''}` | `/routes/subroutes/meeting${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/main/login`; params?: Router.UnknownInputParams; } | { pathname: `/main/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/main/SignupPassword`; params?: Router.UnknownInputParams; } | { pathname: `/main/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/modal/Profile-form`; params?: Router.UnknownInputParams; } | { pathname: `/routes/join`; params?: Router.UnknownInputParams; } | { pathname: `/routes/meet`; params?: Router.UnknownInputParams; } | { pathname: `/routes/profile`; params?: Router.UnknownInputParams; } | { pathname: `/routes/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/routes/subroutes/meeting`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
